---
title: "Quant_reg"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr) 
library(quantreg)
library(ggplot2)
library(tidyverse)
getwd()
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",

  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Read in Cal EnviroScreen Data
```{r}
air_pollution_data = read_csv(file = "/Users/tanyabutt/Desktop/p8332_adv_methods_proj/p8332_final_project/dat_complete.csv") 

air_pollution_data = janitor::clean_names(air_pollution_data) %>% 
  mutate(asln=ifelse(arsenic==0, log(0.01), log(arsenic)), 
                                       uln=ifelse(uranium==0, log(0.01), log(uranium)))
``` 

```{r}
# Does the central tendency (median) vary by annual PM2.5? 
# Median Model 
### Outcome - Census tract level cardiovascular disease hospitalization rate
# median is 50th percentile, so tau = 0.5

Mod50th <- rq(cardiovas ~ pm2_5 + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = 0.5)

summary(Mod50th, alpha = 0.05)

Coeff.Mod50th <- summary(Mod50th, alpha = 0.05)$coefficients

Coeff.Mod50th.PM2.5 <- Coeff.Mod50th[2,1:3]
print(paste0("Association for PM2.5 and 50th percentile CVD Hospitalization: ", 
             round(Coeff.Mod50th.PM2.5[1], 3), " 95% CI: (",
             round(Coeff.Mod50th.PM2.5[2], 3), ", ", 
             round(Coeff.Mod50th.PM2.5[3], 3), ")"))
```

```{r}
# Mean Model w/ PM2.5
ModMean <- lm(cardiovas ~ pm2_5 + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data)

coeff.table  <- data.frame(Fit.Mod50th = summary(Mod50th)$coefficients[,1],
                           Fit.ModMean = summary(ModMean)$coefficients[,1])

coeff.table <- coeff.table %>% 
  #compute percentage difference
  mutate(PercentDiff = 100*(Fit.Mod50th - Fit.ModMean)/Fit.ModMean) %>% 
  # round numbers 
  mutate(Fit.Mod50th   = round(Fit.Mod50th, 3), 
         Fit.ModMean = round(Fit.ModMean, 3),
         PercentDiff   = round(PercentDiff, 1))

coeff.table

Coeff.ModMean.PM2.5 <- summary(ModMean)$coefficients[2,]
ModMean.Beta.pm.fit <- summary(ModMean)$coefficients[2,1]
ModMean.Beta.pm.se  <- summary(ModMean)$coefficients[2,2]
ModMean.Beta.pm.lci <- ModMean.Beta.pm.fit - 1.96 * ModMean.Beta.pm.se
ModMean.Beta.pm.uci <- ModMean.Beta.pm.fit + 1.96 * ModMean.Beta.pm.se

print(paste0("Association for PM2.5 and Mean CVD Hospitalization Rate: ", 
             round(ModMean.Beta.pm.fit, 3), " 95% CI: (",
             round(ModMean.Beta.pm.lci, 3), ", ", 
             round(ModMean.Beta.pm.uci, 3), ")"))
print(paste0("Association for PM2.5 and 50th percentile CVD Hospitalization Rate: ", 
             round(Coeff.Mod50th.PM2.5[1], 3), " 95% CI: (",
             round(Coeff.Mod50th.PM2.5[2], 3), ", ", 
             round(Coeff.Mod50th.PM2.5[3], 3), ")"))
```

```{r}
# Combining estimates from mean and median model into single data frame
# Visualizing results
coeff.table <- data.frame(
  ModelName = c("Mean Model", "Median Model"), 
  coeff = c(ModMean.Beta.pm.fit, Coeff.Mod50th.PM2.5[1]), 
  lci = c(ModMean.Beta.pm.lci, Coeff.Mod50th.PM2.5[2]), 
  uci = c(ModMean.Beta.pm.uci, Coeff.Mod50th.PM2.5[3]) )

coeff.table

ForestPlotMeanMedian <- ggplot(data = coeff.table, 
  aes( 
      x = ModelName,  
      y = coeff,      
      ymin = lci,     
      ymax = uci)) +  
  geom_pointrange() +   
  geom_errorbar() +      
  geom_hline(aes(yintercept = 0.0), lty = 2) +
  xlab("Model Name") +    
  ylab(expression("Coefficient for PM"[2.5]~" (95% CI)"))

ForestPlotMeanMedian
```

```{r}
# Multiple Quantiles- PM2.5
TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(pm2_5) + educat_p + poverty_p + unempl_p
              + hous_burd_p, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar() +                 
  geom_hline(aes(yintercept = 0.0), lty = 2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for PM"[2.5]~" (95% CI)"))

ForestPlot.Mods
```

```{r}
# Multiple Quantiles - Tox Release

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(tox_rel) + educat_p + poverty_p + unempl_p
              + hous_burd_p, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Toxic Release (95% CI)"))

ForestPlot.Mods
```

```{r, eval=false}
# 6c Plot Multiple Quantiles - Ozone

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(ozone) + educat_p + poverty_p + unempl_p
              + hous_burd_p, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Ozone (95% CI)"))

ForestPlot.Mods
```

```{r}
# 6c Plot Multiple Quantiles - Diesel PM

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(diesel_pm) + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Diesel PM (95% CI)"))

ForestPlot.Mods
```

```{r}
# 6c Plot Multiple Quantiles - Traffic

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(traffic) + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Traffic (95% CI)"))

ForestPlot.Mods
```

```{r}
# 6c Plot Multiple Quantiles - pesticides

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ log(pesticide) + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Presticides (95% CI)"))

ForestPlot.Mods
```


```{r}
# 6c Plot Multiple Quantiles - arsenic

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ asln + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Arsenic (95% CI)"))

ForestPlot.Mods
```


```{r}
# 6c Plot Multiple Quantiles - cadmium

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ cadmium + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Cadmium (95% CI)"))

ForestPlot.Mods
```

```{r}
# 6c Plot Multiple Quantiles - lead
TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ lead + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Lead (95% CI)"))

ForestPlot.Mods
```


```{r}
# 6c Plot Multiple Quantiles - nitrate

TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ nitrate + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Nitrate (95% CI)"))

ForestPlot.Mods
```

```{r}
# 6c Plot Multiple Quantiles - uranium
TauList <- seq(0.1, 0.9, by = 0.1)
TauList

qr.Mods  <- rq(cardiovas ~ uln + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_10th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_20th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_30th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])
Model_40th   <- c(summary.qr.Mods[[4]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[5]]$coefficients[2,1:3])
Model_60th   <- c(summary.qr.Mods[[6]]$coefficients[2,1:3])
Model_70th   <- c(summary.qr.Mods[[7]]$coefficients[2,1:3])
Model_80th   <- c(summary.qr.Mods[[8]]$coefficients[2,1:3])
Model_90th   <- c(summary.qr.Mods[[9]]$coefficients[2,1:3])

coeff.table <- rbind(Model_10th, Model_20th, Model_30th, Model_40th, 
                     Model_50th, Model_60th, Model_70th, Model_80th, 
                     Model_90th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE) 

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("10th", "20th", "30th", "40th","50th", "60th", 
                               "70th", "80th", "90th"))

ForestPlot.Mods <- ggplot(data=coeff.table, 
                  aes(x=ModelName,  
                      y=coeff,      
                      ymin=lci,     
                      ymax=uci)) + 
  geom_pointrange() +                       
  geom_errorbar()+                 
  geom_hline(aes(yintercept=0.0), lty=2) + 
  xlab("CVD Quantile") +              
  ylab(expression("Coefficient for Uranium (95% CI)"))

ForestPlot.Mods
```


```{r}
####****************************************************
#### Footnote 3: Interactions in Linear Regression  ####
####****************************************************

# Does the association between county-level annual PM2.5 and county average BMI 
# vary by climate region? 
# Let's add an interaction term 

# F3a Fit regression model 

mod.interaction <- lm(cardiovas ~ pm2_5*poverty +pm2_5 + educatn + poverty + unempl + hous_burd , data = air_pollution_data ,na.action = na.omit)
# F3b Review Model  

summary(mod.interaction)
```

```{r}
# pm2_5 -qartiles 
# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ pm2_5 + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for PM2.5"))

ForestPlot.Mods
```

```{r}
# diesel pm
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ diesel_pm + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for Diesel PM"))

ForestPlot.Mods
```


```{r}
# ozone
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ ozone + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for Ozone"))

ForestPlot.Mods
```


```{r}
# pesticide
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ pesticide + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for Pesticide"))

ForestPlot.Mods
```


```{r}
# tox release
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ tox_rel + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for Toxic Release"))

ForestPlot.Mods
```


```{r}
# traffic
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ traffic + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for Traffic"))

ForestPlot.Mods
```


```{r}
# arsenic
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ arsenic + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for arsenic"))

ForestPlot.Mods
```


```{r}
# cadmium 
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ arsenic + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for cadmium"))

ForestPlot.Mods
```


```{r}
# lead
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ lead_y + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for arsenic"))

ForestPlot.Mods
```


```{r}
# uranium 
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ uranium + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for uranium"))

ForestPlot.Mods
```


```{r}
# nitrate
# we can just use the same procedure as before, 
# but with additional models for every quantile of interest

# 6c.i Create the models
# seq() creates a sequence with intervals set by the by arguement 

TauList <- seq(0.25, 0.75, by = 0.25)
TauList

qr.Mods  <- rq(cardiovas ~ nitrate + educatn + poverty + unempl
              + hous_burd, data = air_pollution_data, tau = TauList)

# 6c.ii Assemble estimates from each model

summary.qr.Mods <- summary(qr.Mods, alpha = 0.05)

Model_25th   <- c(summary.qr.Mods[[1]]$coefficients[2,1:3])
Model_50th   <- c(summary.qr.Mods[[2]]$coefficients[2,1:3])
Model_75th   <- c(summary.qr.Mods[[3]]$coefficients[2,1:3])


# create dataframe 

coeff.table <- rbind(Model_25th, Model_50th, Model_75th)

coeff.table <- as.data.frame(coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(coeff.table) <- c("coeff", "lci", "uci")
coeff.table        <- coeff.table %>% 
          mutate(ModelName = c("25th", "50th", "75th"))

# 6b.ii Plot

ForestPlot.Mods <- ggplot(data=coeff.table, # defines what dataset we are using
                  aes(x=ModelName,  # defines variable for the x axis
                      y=coeff,      # defines the variable for the point along the y axis
                      ymin=lci,     # defines the lower bound of the confidence interval
                      ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +               # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+                  # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("CVD Quantile") +              # labels for axes
  ylab(expression("Coefficient for nitrate"))

ForestPlot.Mods
```