---
title: "CalEnviroScreen describe"
date: "2/17/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(data.table)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(sf)
library(corrplot)
library(Hmisc)
library(splines)
library(mgcv)
```

## Load data

```{r, message=FALSE, warning=FALSE}

dat<- st_read(dsn = "C:/Users/dnmed/OneDrive - cumc.columbia.edu/AAMEHS/OEHHA", 
                layer = "CES4 Final Shapefile", geometry_column = "geometry")

#replace -999 with NA
dat<- dat %>% 
  mutate_if(is.numeric, ~na_if(., -999))

#summary(dat)

dat.dw<- read_csv("C:/Users/dnmed/OneDrive - cumc.columbia.edu/As Cancer Project/Data/ces20drinkingwaterresultsbycontaminant.csv")

#convert to numeric
dat.dw[,6:31]<- apply(dat.dw[,6:31], 2, as.numeric)


#colnames(dat)
#colnames(dat.dw)

dat_merge<- dat %>% full_join(dat.dw[,c(1,6:31)], by=c("Tract"="Census Tract"))

dat_merge_sf<- dat_merge

#drop geometry for summarizing bc it sometimes produces an error
dat_merge<- dat_merge %>% st_drop_geometry()

```

## Summarize data 

### Drinking water contaminants

```{r, fig.height = 5, fig.width = 5}

#summary(dat_merge)

#Metals in drinking water 

summary(dat_merge$Arsenic)
summary(dat_merge$Uranium)
summary(dat_merge$Cadmium)
summary(dat_merge$Lead.y)


hist(dat_merge$Arsenic)
hist(dat_merge$Uranium)
hist(dat_merge$Cadmium)
hist(dat_merge$Lead.y)

#Fuller distribution

quantile(dat_merge$Arsenic, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$Uranium, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$Cadmium, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$Lead.y, seq(0,1,by=0.05), na.rm = TRUE)



#dat_merge<- dat_merge %>% mutate(ArsenicQ= cut2(Arsenic, g=4), 
#                   UraniumQ=cut2(Uranium, g=4), 
#                   CadmiumQ=cut2(Cadmium,g=4), 
#                   LeadQ= cut2(Lead.y, g=4))

#table(dat_merge$ArsenicQ)
#table(dat_merge$UraniumQ)
#table(dat_merge$CadmiumQ)
#able(dat_merge$LeadQ)



#Nitrate better distribution 

summary(dat_merge$Nitrate)
hist(dat_merge$Nitrate)
quantile(dat_merge$Nitrate, seq(0,1,by=0.05), na.rm = TRUE)


#correlation 

metals<- dat_merge %>% select(Arsenic, Uranium, Cadmium, Lead.y, Nitrate)
cormetal<- cor(metals,use="complete.obs",method = "spearman")
corrplot.mixed(cormetal, lower.col = "black")




```



### Air pollution 

```{r, fig.height = 5, fig.width = 5}

summary(dat_merge$Ozone)
summary(dat_merge$PM2_5)
summary(dat_merge$DieselPM)
summary(dat_merge$Tox_Rel)
summary(dat_merge$Traffic)

hist(dat_merge$Ozone)
hist(dat_merge$PM2_5)
hist(dat_merge$DieselPM)
hist(dat_merge$Tox_Rel)
hist(dat_merge$Traffic)




#Fuller distribution

quantile(dat_merge$Ozone, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$PM2_5, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$DieselPM, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$Tox_Rel, seq(0,1,by=0.05), na.rm = TRUE)
quantile(dat_merge$Traffic, seq(0,1,by=0.05), na.rm = TRUE)




#correlation 

AP<- dat_merge %>% select(Ozone, PM2_5, DieselPM, Tox_Rel, Traffic)
corAP<- cor(AP,use="complete.obs",method = "spearman")
corrplot.mixed(corAP, lower.col = "black")

#Lead in homes also a good distribution 

summary(dat_merge$Lead.x)
hist(dat_merge$Lead.x)
quantile(dat_merge$Lead.x, seq(0,1,by=0.05), na.rm = TRUE)




```

### Maps 

```{r}
library(viridis)

#ggplot(dat_merge_sf) +
#  geom_sf(aes(fill = Arsenic))+
#  scale_fill_gradientn(colours=rev(magma(6)), trans="sqrt")
  
#missing 227 tracts
summary(dat_merge$LowBirtWt)
#CVD only missing 11 tracts
#summary(dat_merge$Cardiovas)


ggplot(dat_merge_sf) +
  geom_sf(aes(fill = LowBirtWt))+
  scale_fill_gradientn(colours=rev(magma(6)), trans="sqrt")
  


```


## Quick models

### Low birth weight

```{r, fig.height = 5, fig.width = 5}


#+Hispanic+White+AfricanAm+NativeAm+OtherMult (add in if want to adjust for race/eth)


#Water exposures

WaterExp<- c("Arsenic", "Uranium", "Cadmium", "Lead.y", "Nitrate")


WaterMod <- lapply(WaterExp, function(i) {
      # STRING INTERPOLATION WITH sprintf, THEN CONVERTED TO FORMULA OBJECT
      iformula <- as.formula(sprintf("LowBirtWt~s(%s)+EducatP+PovertyP+UnemplP+HousBurdP", i))  
      gam(iformula, data=dat_merge, family = "quasipoisson") 
  
 
})


plot.gam(WaterMod[[1]])
abline(h=0)
plot.gam(WaterMod[[2]])
abline(h=0)
plot.gam(WaterMod[[3]])
abline(h=0)
plot.gam(WaterMod[[4]])
abline(h=0)
plot.gam(WaterMod[[5]])
abline(h=0)

#Air pollution (and housing lead)

APExp<- c("Ozone", "PM2_5", "DieselPM", "Tox_Rel", "Traffic", "Lead.x")


APMod <- lapply(APExp, function(i) {
      # STRING INTERPOLATION WITH sprintf, THEN CONVERTED TO FORMULA OBJECT
      iformula <- as.formula(sprintf("LowBirtWt~s(%s)+EducatP+PovertyP+UnemplP+HousBurdP", i))  
      gam(iformula, data=dat_merge, family = "quasipoisson") 
  
 
})


plot.gam(APMod[[1]])
abline(h=0)
plot.gam(APMod[[2]])
abline(h=0)
plot.gam(APMod[[3]])
abline(h=0)
plot.gam(APMod[[4]])
abline(h=0)
plot.gam(APMod[[5]])
abline(h=0)
plot.gam(APMod[[6]])
abline(h=0)



```

### CVD 



```{r}




#+Hispanic+White+AfricanAm+NativeAm+OtherMult (add in if want to adjust for race/eth)


#Water exposures

WaterExp<- c("Arsenic", "Uranium", "Cadmium", "Lead.y", "Nitrate")


WaterMod <- lapply(WaterExp, function(i) {
      # STRING INTERPOLATION WITH sprintf, THEN CONVERTED TO FORMULA OBJECT
      iformula <- as.formula(sprintf("Cardiovas~s(%s)+EducatP+PovertyP+UnemplP+HousBurdP", i))  
      gam(iformula, data=dat_merge, family = "quasipoisson") 
  
 
})


plot.gam(WaterMod[[1]])
abline(h=0)
plot.gam(WaterMod[[2]])
abline(h=0)
plot.gam(WaterMod[[3]])
abline(h=0)
plot.gam(WaterMod[[4]])
abline(h=0)
plot.gam(WaterMod[[5]])
abline(h=0)

#Air pollution (and housing lead)

APExp<- c("Ozone", "PM2_5", "DieselPM", "Tox_Rel", "Traffic", "Lead.x")


APMod <- lapply(APExp, function(i) {
      # STRING INTERPOLATION WITH sprintf, THEN CONVERTED TO FORMULA OBJECT
      iformula <- as.formula(sprintf("Cardiovas~s(%s)+EducatP+PovertyP+UnemplP+HousBurdP", i))  
      gam(iformula, data=dat_merge,  family = "quasipoisson") 
  
 
})


plot.gam(APMod[[1]])
abline(h=0)
plot.gam(APMod[[2]])
abline(h=0)
plot.gam(APMod[[3]])
abline(h=0)
plot.gam(APMod[[4]])
abline(h=0)
plot.gam(APMod[[5]])
abline(h=0)
plot.gam(APMod[[6]])
abline(h=0)







```


```{r, include=FALSE}


dat_merge %>% group_by(cut2(Arsenic, cuts = c(0,0.5,1,3,5,10))) %>% summarise(n())

dat_merge<- dat_merge %>% mutate(ArsenicQ=cut2(Arsenic, cuts = c(0,0.5,1,3,5,10)))

dat_merge<- dat_merge %>% mutate(CardiovasINT= as.integer(Cardiovas))

dat_merge<- dat_merge %>% mutate(N=rep(10000, nrow(.)))

mod<- gam(Cardiovas~ArsenicQ+s(Ozone)+s(PM2_5)+EducatP+PovertyP+UnemplP+HousBurdP+offset(log(N)), data=dat_merge,  family = "poisson") 

summary(mod)

```
